---
extends:
  - "@commitlint/config-conventional"

rules:
  header-max-length:
    - 2
    - always
    - 72
  subject-case:
    - 2
    - never
    - - sentence-case
      - start-case
      - pascal-case
      - upper-case
  scope-case:
    - 2
    - always
    - lower-case
  type-enum:
    - 2
    - always
    - - feat
      - fix
      - docs
      - refactor
      - perf
      - test
      - ci
      - chore
      - revert
